# Generated by Django 5.1.6 on 2026-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='Bevétel', max_length=100),
            preserve_default=False,
        ),
    ]
