# Generated by Django 5.1.6 on 2026-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default='2026-06-14'),
            preserve_default=False,
        ),
    ]
